# Generated by Django 4.2.30 on 2026-07-28 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_alter_ownerprofile_options_and_more'),
        ('pgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['name'], 'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='pgimage',
            options={'ordering': ['-is_primary', '-uploaded_at'], 'verbose_name': 'PG Image', 'verbose_name_plural': 'PG Images'},
        ),
        migrations.AlterModelOptions(
            name='pglisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'PG Listing', 'verbose_name_plural': 'PG Listings'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['pg', 'sharing_type'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AddField(
            model_name='pgimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Uploaded At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pglisting',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon Class/URL'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pgimage',
            name='image',
            field=models.ImageField(upload_to='pg_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pgimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Is Primary'),
        ),
        migrations.AlterField(
            model_name='pgimage',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pgs.pglisting', verbose_name='PG Listing'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='pgs', to='pgs.amenity', verbose_name='Amenities'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='gender_type',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('coed', 'Co-Ed')], max_length=10, verbose_name='Gender Type'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='house_rules',
            field=models.TextField(blank=True, null=True, verbose_name='House Rules'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='name',
            field=models.CharField(max_length=255, verbose_name='PG Name'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgs', to='owners.ownerprofile', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='state',
            field=models.CharField(db_index=True, max_length=100, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='zip_code',
            field=models.CharField(max_length=20, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='room',
            name='available_beds',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Available Beds'),
        ),
        migrations.AlterField(
            model_name='room',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Deposit Amount'),
        ),
        migrations.AlterField(
            model_name='room',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pgs.pglisting', verbose_name='PG Listing'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price Per Month'),
        ),
        migrations.AlterField(
            model_name='room',
            name='sharing_type',
            field=models.PositiveIntegerField(help_text='e.g., 1 for single, 2 for double sharing', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Sharing Type'),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_beds',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Beds'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('pg', 'sharing_type')},
        ),
    ]
