# Generated by Django 4.2.30 on 2026-07-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0002_alter_amenity_options_alter_pgimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pglisting',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
