# Generated by Django 4.2.30 on 2026-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0003_pglisting_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgimage',
            name='image',
            field=models.ImageField(upload_to='pg_images/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='gender_type',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('coed', 'Co-Ed')], db_index=True, max_length=10, verbose_name='Gender Type'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Approved'),
        ),
    ]
