# Generated by Django 4.2.30 on 2026-07-28 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0002_alter_amenity_options_alter_pgimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparelist',
            options={'ordering': ['-added_at'], 'verbose_name': 'Compare List Item', 'verbose_name_plural': 'Compare List Items'},
        ),
        migrations.AlterField(
            model_name='comparelist',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added At'),
        ),
        migrations.AlterField(
            model_name='comparelist',
            name='pg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_by', to='pgs.pglisting', verbose_name='PG Listing'),
        ),
        migrations.AlterField(
            model_name='comparelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_list', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
