# Generated by Django 4.2.30 on 2026-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner'), ('admin', 'Admin')], default='tenant', help_text='Select the role for the user.', max_length=10, verbose_name='Role'),
        ),
    ]
